### ISSUE TITLE
Resolution Issues

### ISSUE THREAD

**Issue by KyleStevenson3** [Sippius/Ashita-v4-addons#4]
I can't get the window large enough to be easily readable with my 4K monitor.

My fix was:
chains.lua:
```
        if (imgui.Begin('chains', true, flags)) then

            if render then
				imgui.SetWindowFontScale(3.0);
                                ...

```

I suggest making the scale factor a value that can be saved/modified at runtime like the other options.

**Comment by Sippius** [comment]
Thanks. I'll look into adding some more configuration.

**Comment by Sippius** [comment]
Added a font scale setting to v0.7
